# Generated by Django 4.2.16 on 2025-04-18 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default commission rate in percentage', max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('poc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_partner_pocs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('enrollment_source', models.CharField(choices=[('direct', 'Direct'), ('channel_partner', 'Channel Partner'), ('university', 'University')], default='direct', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPartnerStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('enrollment_date', models.DateField()),
                ('transfer_price', models.DecimalField(decimal_places=2, help_text='Actual transfer price for this student', max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Commission amount for this student', max_digits=12)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_partner_students', to='core.batch')),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.channelpartner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_partner_enrollments', to='core.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelPartnerProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('transfer_price', models.DecimalField(decimal_places=2, help_text="Partner's transfer price for this program", max_digits=12)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate override for this program', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.channelpartner')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_partners', to='core.program')),
            ],
            options={
                'unique_together': {('channel_partner', 'program')},
            },
        ),
    ]
