# Generated by Django 4.2.16 on 2024-12-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_rename_course_to_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='oem_transfer_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Override contract's OEM transfer price for this batch", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='batchsnapshot',
            name='oem_transfer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='OEM transfer price at the time of snapshot', max_digits=12),
        ),
        migrations.AddField(
            model_name='billing',
            name='total_oem_transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
