# Generated by Django 4.2.16 on 2024-12-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_batch_oem_transfer_price_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.university'),
            preserve_default=False,
        ),
    ]
