# Generated by Django 4.2.16 on 2025-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_channelpartnerstudent_batch_programbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbatch',
            name='cost_per_student',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
