# Generated by Django 4.2.16 on 2024-12-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contract_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
