# Generated by Django 4.2.16 on 2025-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_programbatch_cost_per_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('provider_poc', 'Provider POC'), ('university_poc', 'University POC'), ('agent', 'Agent')], max_length=20, null=True),
        ),
    ]
