# Generated by Django 4.2.16 on 2024-12-24 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchsnapshot',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='batchsnapshot',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='batchsnapshot',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='batch_snapshots',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='total_oem_transfer_amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='total_payments',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='reminder_recipients',
        ),
        migrations.AddField(
            model_name='batchsnapshot',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_snapshots', to='core.billing'),
        ),
        migrations.AlterField(
            model_name='batchsnapshot',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.batch'),
        ),
        migrations.CreateModel(
            name='PaymentScheduleRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.paymentschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to='payments/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.payment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
