# Generated by Django 4.2.16 on 2025-08-09 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invitees', models.TextField(blank=True, help_text='Comma separated email addresses', null=True)),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('outlook_calendar_id', models.CharField(blank=True, help_text='Outlook Calendar Event ID', max_length=255, null=True)),
                ('outlook_calendar_url', models.URLField(blank=True, help_text='Outlook Calendar Event URL', null=True)),
                ('notion_page_id', models.CharField(blank=True, help_text='Notion Page ID', max_length=255, null=True)),
                ('notion_page_url', models.URLField(blank=True, help_text='Notion Page URL', null=True)),
                ('integration_status', models.CharField(choices=[('pending', 'Pending'), ('outlook_created', 'Outlook Created'), ('notion_created', 'Notion Created'), ('both_created', 'Both Created'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('integration_notes', models.TextField(blank=True, help_text='Notes about integration status', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.batch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.university')),
            ],
            options={
                'verbose_name': 'University Event',
                'verbose_name_plural': 'University Events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
