# Generated by Django 4.2.16 on 2024-12-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_batchsnapshot_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billing',
            name='total_oem_transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billing',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
