# Generated by Django 4.2.16 on 2024-12-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_billing_balance_due_billing_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
