# Generated by Django 4.2.16 on 2025-08-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_universityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftGraphToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('token_type', models.CharField(choices=[('client_credentials', 'Client Credentials'), ('delegated', 'Delegated')], default='client_credentials', max_length=20)),
                ('access_token', models.TextField(help_text='The access token for Microsoft Graph API')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token (for delegated auth)', null=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp')),
                ('scopes', models.TextField(blank=True, help_text='Comma-separated list of scopes', null=True)),
                ('user_id', models.CharField(blank=True, help_text='User ID for delegated tokens', max_length=255, null=True)),
                ('tenant_id', models.CharField(blank=True, help_text='Tenant ID', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time this token was used')),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Number of consecutive errors with this token')),
                ('last_error', models.TextField(blank=True, help_text='Last error message', null=True)),
            ],
            options={
                'verbose_name': 'Microsoft Graph Token',
                'verbose_name_plural': 'Microsoft Graph Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
