# Generated by Django 4.2.16 on 2024-12-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='Invoice', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='Payment', max_length=255),
        ),
    ]
