# Generated by Django 4.2.16 on 2025-08-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_microsoft_graph_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsoftgraphtoken',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='microsoftgraphtoken',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='microsoftgraphtoken',
            name='token_type',
            field=models.CharField(choices=[('client_credentials', 'Client Credentials')], default='client_credentials', max_length=20),
        ),
    ]
