# Generated by Django 4.2.16 on 2024-12-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invoice_name_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paid', 'Paid'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
