# Generated by Django 4.2.16 on 2025-08-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_microsoftgraphtoken_refresh_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MicrosoftGraphToken',
        ),
        migrations.RemoveField(
            model_name='universityevent',
            name='outlook_calendar_id',
        ),
        migrations.RemoveField(
            model_name='universityevent',
            name='outlook_calendar_url',
        ),
        migrations.AddField(
            model_name='universityevent',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When emails were sent', null=True),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='email_sent_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of emails sent'),
        ),
        migrations.AlterField(
            model_name='universityevent',
            name='integration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('email_sent', 'Email Sent'), ('notion_created', 'Notion Created'), ('both_completed', 'Both Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
