# Generated by Django 4.2.16 on 2025-09-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_email_integration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('travel', 'Travel'), ('operations', 'Operations'), ('logistics', 'Logistics'), ('venue', 'Venue'), ('speaker', 'Speaker'), ('other', 'Other')], default='other', max_length=50)),
                ('incurred_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.batch')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.universityevent')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.university')),
            ],
            options={
                'ordering': ['-incurred_date', '-created_at'],
                'indexes': [models.Index(fields=['university', 'incurred_date'], name='core_expens_univers_3a7f04_idx'), models.Index(fields=['batch', 'incurred_date'], name='core_expens_batch_i_baa237_idx'), models.Index(fields=['event'], name='core_expens_event_i_11d219_idx')],
            },
        ),
    ]
