# Generated by Django 4.2.16 on 2025-10-15 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('provider_poc', 'Provider POC'), ('university_poc', 'University POC'), ('agent', 'Agent'), ('staff', 'Staff')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='StaffUniversityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.university')),
            ],
            options={
                'verbose_name': 'Staff University Assignment',
                'verbose_name_plural': 'Staff University Assignments',
                'unique_together': {('staff', 'university')},
            },
        ),
    ]
