# Generated by Django 4.2.16 on 2025-10-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_staff_role_and_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='cost_per_student_override',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='oem_transfer_price_override',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='tax_rate_override',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='cost_per_student',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='oem_transfer_price',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='streams',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='batch',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.university'),
        ),
        migrations.AddField(
            model_name='contract',
            name='end_year',
            field=models.PositiveIntegerField(default=2025, help_text='Contract end year'),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_year',
            field=models.PositiveIntegerField(default=2024, help_text='Contract start year'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContractStreamPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('year', models.PositiveIntegerField(help_text='Year for this pricing')),
                ('cost_per_student', models.DecimalField(decimal_places=2, help_text='Cost per student for this stream/year', max_digits=12)),
                ('oem_transfer_price', models.DecimalField(decimal_places=2, help_text='OEM transfer price for this stream/year', max_digits=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_pricing', to='core.contract')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_pricing', to='core.stream')),
                ('tax_rate', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stream_pricing', to='core.taxrate')),
            ],
            options={
                'ordering': ['stream__name', 'year'],
                'unique_together': {('contract', 'stream', 'year')},
            },
        ),
    ]
