# Generated by Django 4.2.16 on 2025-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contract_stream_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityevent',
            name='email_sent_at',
        ),
        migrations.RemoveField(
            model_name='universityevent',
            name='email_sent_count',
        ),
        migrations.AlterField(
            model_name='universityevent',
            name='integration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('notion_created', 'Notion Created'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
