# Generated by Django 4.2.16 on 2025-10-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_email_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdocument',
            name='document_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice'), ('bank_statement', 'Bank Statement'), ('approval', 'Approval Document'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='file',
            field=models.FileField(upload_to='oem_payments/documents/'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('oem', 'university')},
        ),
        migrations.CreateModel(
            name='OEMPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('oem_transfer', 'OEM Transfer Payment'), ('commission', 'Commission Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('other', 'Other')], max_length=20)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField()),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount included in payment', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount after tax', max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_oem_payments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oem_payments', to='core.batch')),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oem_payments', to='core.billing')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oem_payments', to='core.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_oem_payments', to=settings.AUTH_USER_MODEL)),
                ('oem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.oem')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.oempayment'),
        ),
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('oem_payment', 'OEM Payment'), ('commission_payment', 'Commission Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField()),
                ('running_balance', models.DecimalField(decimal_places=2, help_text='Running balance after this transaction', max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.billing')),
                ('oem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.oem')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.oempayment')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.university')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'transaction_date'], name='core_paymen_transac_d51fab_idx'), models.Index(fields=['oem', 'transaction_date'], name='core_paymen_oem_id_6f39dc_idx'), models.Index(fields=['university', 'transaction_date'], name='core_paymen_univers_b911c3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='oempayment',
            index=models.Index(fields=['oem', 'payment_date'], name='core_oempay_oem_id_73917d_idx'),
        ),
        migrations.AddIndex(
            model_name='oempayment',
            index=models.Index(fields=['status', 'payment_date'], name='core_oempay_status_21475a_idx'),
        ),
        migrations.AddIndex(
            model_name='oempayment',
            index=models.Index(fields=['payment_type', 'payment_date'], name='core_oempay_payment_025cb6_idx'),
        ),
    ]
