# Generated by Django 4.2.16 on 2025-10-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_contract_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractstreampricing',
            options={'ordering': ['program__name', 'stream__name', 'year']},
        ),
        migrations.AlterUniqueTogether(
            name='contractstreampricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contractstreampricing',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stream_pricing', to='core.program'),
        ),
        migrations.AlterField(
            model_name='contractstreampricing',
            name='cost_per_student',
            field=models.DecimalField(decimal_places=2, help_text='Cost per student for this program/stream/year', max_digits=12),
        ),
        migrations.AlterField(
            model_name='contractstreampricing',
            name='oem_transfer_price',
            field=models.DecimalField(decimal_places=2, help_text='OEM transfer price for this program/stream/year', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='contractstreampricing',
            unique_together={('contract', 'program', 'stream', 'year')},
        ),
    ]
