# Generated by Django 4.2.16 on 2025-10-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_program_to_contract_stream_pricing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('name', 'oem', 'university')},
        ),
    ]
