# Generated by Django 4.2.16 on 2025-10-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_update_contract_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.program'),
        ),
    ]
