# Generated by Django 4.2.16 on 2025-10-31 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_batch_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='oempayment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice this OEM payment is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_oem_payments', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='paymentledger',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice this ledger entry is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.invoice'),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('oem_payment', 'OEM Payment'), ('commission_payment', 'Commission Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('tds', 'TDS (Tax Deducted at Source)')], max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceTDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, help_text='TDS amount deducted at source. IMPORTANT: This amount NEVER hits our account. University deducts TDS and pays it directly to government on our behalf. We can claim it back only if we have no tax liability or tax rebate.', max_digits=12)),
                ('tds_rate', models.DecimalField(decimal_places=2, help_text='TDS rate percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('deduction_date', models.DateField(help_text='Date when TDS was deducted at source')),
                ('reference_number', models.CharField(blank=True, help_text='TDS certificate or form number', max_length=255, null=True)),
                ('certificate_type', models.CharField(blank=True, choices=[('form_16a', 'Form 16A'), ('form_16b', 'Form 16B'), ('certificate', 'TDS Certificate'), ('other', 'Other')], help_text='Type of TDS certificate', max_length=20, null=True)),
                ('certificate_document', models.FileField(blank=True, help_text='TDS certificate document', null=True, upload_to='invoices/tds/')),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_entries', to='core.invoice')),
            ],
            options={
                'verbose_name': 'Invoice TDS',
                'verbose_name_plural': 'Invoice TDS Entries',
                'ordering': ['-deduction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceOEMPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField()),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invoice_oem_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oem_payments', to='core.invoice')),
                ('oem_payment', models.ForeignKey(blank=True, help_text='Linked OEMPayment entry for ledger tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_oem_payments', to='core.oempayment')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentledger',
            name='tds_entry',
            field=models.ForeignKey(blank=True, help_text='TDS entry this ledger entry is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.invoicetds'),
        ),
        migrations.AddIndex(
            model_name='invoicetds',
            index=models.Index(fields=['invoice', 'deduction_date'], name='core_invoic_invoice_62dd29_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceoempayment',
            index=models.Index(fields=['invoice', 'payment_date'], name='core_invoic_invoice_efad94_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceoempayment',
            index=models.Index(fields=['status', 'payment_date'], name='core_invoic_status_086fe1_idx'),
        ),
    ]
