# Generated by Django 4.2.16 on 2025-10-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_oempayment_invoice_paymentledger_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentledger',
            name='tds_entry',
        ),
        migrations.AlterField(
            model_name='invoiceoempayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('oem_payment', 'OEM Payment'), ('commission_payment', 'Commission Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
