# Generated by Django 4.2.16 on 2025-11-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_paymentledger_tds_entry_and_more'),
    ]

    operations = [
    ]
