# Generated by Django 4.2.16 on 2025-11-03 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fix_paymentdocument_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdocument',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='file',
            field=models.FileField(upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.payment'),
        ),
        migrations.CreateModel(
            name='OEMPaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to='oem_payments/documents/')),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice'), ('bank_statement', 'Bank Statement'), ('approval', 'Approval Document'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.oempayment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
