# Generated by Django 4.2.16 on 2025-11-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_paymentdocument_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('entry_date', models.DateField()),
                ('account', models.CharField(choices=[('cash', 'Cash'), ('accounts_receivable', 'Accounts Receivable'), ('oem_payable', 'OEM Payable'), ('expense', 'Expense'), ('commission_expense', 'Commission Expense'), ('revenue', 'Revenue'), ('tds_payable', 'TDS Payable')], max_length=64)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('memo', models.TextField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('reversing', models.BooleanField(default=False, help_text='True when this line reverses the effect of a prior line.')),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_lines', to='core.billing')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_lines', to='core.expense')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_lines', to='core.invoice')),
                ('oem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_lines', to='core.oem')),
                ('oem_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_lines', to='core.oempayment')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_lines', to='core.payment')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_lines', to='core.university')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['account'], name='core_ledger_account_aa561f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['entry_date'], name='core_ledger_entry_da62d9_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['university', 'account'], name='core_ledger_universi_d01dda_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['university', 'entry_date'], name='core_ledger_universi_1afaff_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['payment'], name='core_ledger_payment_6ccd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['oem_payment'], name='core_ledger_oem_pay_7f93d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerline',
            index=models.Index(fields=['expense'], name='core_ledger_expense_c98022_idx'),
        ),
        migrations.DeleteModel(
            name='PaymentLedger',
        ),
    ]

