# Generated by Django 4.2.16 on 2025-11-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_append_only_ledger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ledgerline',
            new_name='core_ledger_account_95daca_idx',
            old_name='core_ledger_account_aa561f_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerline',
            new_name='core_ledger_entry_d_70509e_idx',
            old_name='core_ledger_entry_da62d9_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerline',
            new_name='core_ledger_univers_16e8ca_idx',
            old_name='core_ledger_universi_d01dda_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerline',
            new_name='core_ledger_univers_af6ec1_idx',
            old_name='core_ledger_universi_1afaff_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerline',
            new_name='core_ledger_payment_f1e4a2_idx',
            old_name='core_ledger_payment_6ccd1b_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerline',
            new_name='core_ledger_oem_pay_35f87e_idx',
            old_name='core_ledger_oem_pay_7f93d2_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerline',
            new_name='core_ledger_expense_fa4e1e_idx',
            old_name='core_ledger_expense_c98022_idx',
        ),
    ]
